title: Prototyping Interactive Objects
description: Description
theme: just-the-docs

url: https://marionkoellehci.github.io/prototyping-interactive-objects

aux_links:
  Template Repository: https://github.com/marionkoellehci/prototyping-interactive-objects
